server:
    port: 8082

spring:
    application:
        name: inventory
    
    kafka:
        bootstrap-server: localhost:9092
        consumer:
            properties:
                spring.json.value.default.type: com.parrino.riccardo.dto.InventoryRequest
                spring.json.trusted.packages: com.parrino.riccardo.dto
        producer:
            properties:
                spring.json.add.type.headers: false
            

