spring:
    application:
        name: inventory
    
    kafka:
        bootstrap-server: localhost:9092
        consumer:
            group-id: my-group
            auto-offset-reset: earliest
            key-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
        producer:
            key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            

